/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;

/**
 *
 * @author PUDGE
 */
public class interface2 extends javax.swing.JFrame {

    boolean setVisible;

    /**
     * Creates new form interface2
     */
    public interface2() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
     public Image getIconImage() {
        Image retValue = null;
        
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelmodulo2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelModulo1 = new javax.swing.JLabel();
        jButtonJugarmodulo1 = new javax.swing.JButton();
        jButtonJugarModulo2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelfondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelmodulo2.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabelmodulo2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelmodulo2.setText("Domina el teclado");
        getContentPane().add(jLabelmodulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 150, 40));

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabelModulo1.setBackground(new java.awt.Color(0, 0, 255));
        jLabelModulo1.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabelModulo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelModulo1.setText("Juega Frases");
        getContentPane().add(jLabelModulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, 40));

        jButtonJugarmodulo1.setBackground(new java.awt.Color(0, 0, 51));
        jButtonJugarmodulo1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJugarmodulo1.setText("¡Jugar!");
        jButtonJugarmodulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugarmodulo1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJugarmodulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 80, 30));

        jButtonJugarModulo2.setBackground(new java.awt.Color(0, 0, 51));
        jButtonJugarModulo2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJugarModulo2.setText("¡Jugar!");
        jButtonJugarModulo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugarModulo2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJugarModulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, 80, 30));

        jButton2.setBackground(new java.awt.Color(0, 0, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(793, 20, 60, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/4856aedb74602c7.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 300, 270));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/4856aedb74602c7.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 290, 290));

        jLabelfondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blue-and-black-wallpaper-hd-smart-phone-mac-desktop-images-windows-1920x1080.jpg"))); // NOI18N
        getContentPane().add(jLabelfondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        interface2interface1 a=new interface2interface1();
       a.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        interface4 a=new interface4();
        a.setVisible(true);
        this.setVisible(false);    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonJugarmodulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugarmodulo1ActionPerformed
        interface2modulo1 a=new interface2modulo1();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonJugarmodulo1ActionPerformed

    private void jButtonJugarModulo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugarModulo2ActionPerformed
       interface2modulo2 a=new interface2modulo2();
       a.setVisible(true);
              this.setVisible(false);

       
    }//GEN-LAST:event_jButtonJugarModulo2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interface2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interface2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interface2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interface2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interface2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonJugarModulo2;
    private javax.swing.JButton jButtonJugarmodulo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelModulo1;
    private javax.swing.JLabel jLabelfondo1;
    private javax.swing.JLabel jLabelmodulo2;
    // End of variables declaration//GEN-END:variables
}
